mailman_dir=Mailman basis directory,3,Standaard
mailman_var=Mailman data directory,3,Zelfde als de basis directory
mailman_cmd=Volledig pad naar de mailman opdracht,3,Automatisch
mailman_templates=Mailman berichten template directory,3,Onder de basis directory
mode=Lijst met alias gemaakte mode,1,1-Toevoegen normale virtgebruikers,0-Gebruik Postfix mail lijst map
cgiuser=Gebruiker die mailman programma's uitvoert als,3,Apache webserver gebruiker
webminurl=URL naar Webmin in de Apache configuratie,3,Automatisch
no_redirects=Apache redirects toevoegen aan de Webmin Mailman module?1.0-Ja,1-Nee
manage_url=URL voor Beheer knop,3,Ingebouwd in Mailman programma wrappers
