mailman_dir=Mailman basis directory,3,Standaard
mailman_var=Mailman data directory,3,Zelfde als de basis directory
mailman_cmd=Volledig pad naar de mailman opdracht,3,Automatisch
mailman_templates=Mailman berichten template directory,3,Onder de basis directory
mode=Lijst van gemaakte alias mode,1,1-Normale virtusers toevoegen,0-Gebruik Postfix maillijst map
cgiuser=Gebruiker die mailman programma uitvoert als,3,Apache webserver gebruiker
webminurl=URL naar Webmin in de Apache configuratie,3,Automatisch
no_redirects=Toevoegen van de Apache redirects aan Webmin Mailman module?,1,0-Ja,1-Nee
manage_url=URL voor Beheer knop,3,Ingebouwd in Mailman programma wrappers
